### ISSUE TITLE
Gather catering schedules

### ISSUE THREAD

**Issue by palkerecsenyi** [MGS-School-Council/my-mgs#15]
Get real data about catering schedules:

- How long a cycle lasts (2 weeks, 3 weeks?)
- How cycles are aligned with terms (do they resume or reset after holidays?)
- What food items are available on each day
  - Whether it's vegetarian, vegan, Halal, or OU-approved Kosher (or any combination)
  - No specific info about allergens is necessary
  - A 2-3 word title and a very short description if applicable for each item on each day
- Which year groups the schedule applies to
  - If there are different menus for different year groups, please report this

**Assigned:** Monty from School Council

**Comment by gezakerecsenyi** [comment]
Is this in progress/is someone assigned to this @palkerecsenyi?

**Comment by palkerecsenyi** [comment]
> Is this in progress/is someone assigned to this @palkerecsenyi?

Read the description please; Monty from School Council is assigned

**Comment by gezakerecsenyi** [comment]
Can we move it to 'In Progress' on the Kanban then? The reason I asked is because I know that progress has already been made in this regard, and yet it's still in 'To do'.
